# Generated by Django 6.0.5 on 2026-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('travel_style', models.CharField(choices=[('luxury', 'Luxury'), ('budget', 'Budget'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('cultural', 'Cultural')], max_length=255)),
                ('interests', models.ManyToManyField(to='core.interest')),
            ],
        ),
    ]
