# Generated by Django 6.0.5 on 2026-05-09 11:00

from django.db import migrations


def seed_interests(apps, schema_editor):
    Interest = apps.get_model("core", "Interest")
    for name in ["Food", "Hiking", "Nightlife", "History", "Shopping", "Nature", "Beaches"]:
        Interest.objects.get_or_create(name=name)



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_interests),
    ]
