# Generated by Django 6.0.5 on 2026-05-09 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Budget for the trip', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='climate_preference',
            field=models.CharField(choices=[('tropical', 'Tropical'), ('temperate', 'Temperate'), ('cold', 'Cold'), ('arid', 'Arid'), ('any', 'Any / Surprise me!')], default='cold', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency for the budget', max_length=10),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='departure_city',
            field=models.CharField(default='dhaka', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration of the trip in days'),
            preserve_default=False,
        ),
    ]
