# Generated by Django 6.0.5 on 2026-05-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questionnaire_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='abroad_trip_flex',
            field=models.BooleanField(default=False, help_text='Whether the user is open to international travel (abroad trips)'),
        ),
    ]
