# Generated by Django 6.0.5 on 2026-05-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questionnaire_abroad_trip_flex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='climate_preference',
            field=models.CharField(choices=[('tropical', 'Tropical'), ('temperate', 'Temperate'), ('cold', 'Cold'), ('arid', 'Arid'), ('mediterranean', 'Mediterranean'), ('any', 'Any / Surprise me!')], max_length=255),
        ),
    ]
