# Generated by Django 6.0.5 on 2026-05-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_questionnaire_climate_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='currency',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='budget',
            field=models.CharField(help_text="Budget for the trip in user's currency", max_length=10),
        ),
    ]
